version: '3'
services:
  frontend:
    build: .
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm start"
    ports:
      - "4200:4200"
